### PR TITLE
Misc improvements and major refactoring

### LINKED ISSUE #20: Receiving c2d messages not working?
Hi,

I am using the device simulator to send `d2c` messages to nRF Cloud and have added my own service type. Works fine.

Now I am trying to receive `c2d` messages from nRF Cloud. According to the device simulator `README.md`, once the simulator displays `subscribed to "dev/<your_tenant_id>/<your_device_id>/jobs/rcv"` it should be _"onboarded and ready to start sending and receiving device messages"_.

However, receiving is not working for me, or maybe I am misunderstanding how it is supposed to work.

I am using the nRF Cloud API with curl to send messages to topic `d/<device_id>/c2d` as well as `d/<device_id>/c2d/r` and I can verify that messages for the `device_id` have been published in nRF Cloud by subscribing with a MQTT tool.

I would expect the device simulator to subscribe to the `c2d` topic(s) and log these incoming messages via the `client.on('message', ...)` callback, but I don't see that happening.

While investigating, I realized I am not seeing a subscription message for `c2d` topic(s) during the device simulator startup, so I added a `c2d` topic in class `NrfDevice.ts`, like
```
		this.topics = {
			d2c: `${mqttMessagesPrefix}d/${deviceId}/d2c`,
			c2d: `${mqttMessagesPrefix}d/${deviceId}/c2d/r`,
			jobs: {
				request: `${stage}/${tenantId}/${deviceId}/jobs/req`,
				receive: `${stage}/${tenantId}/${deviceId}/jobs/rcv`,
				update: `${stage}/${tenantId}/${deviceId}/jobs/update`,
			},
```
but the `c2d` topic is still not subscribed during device simulator startup.

Is there an issue with the device simulator code with regard to receiving `c2d` messages? Or am I misunderstanding something?

Thanks,
-- Terrence

### PR DESCRIPTION
**Pull request by savvyintegrations**
In researching answers for https://devzone.nordicsemi.com/support-private/support/333396, it became apparent that we need to add support for [MQTT Team devices](https://docs.nordicsemi.com/bundle/nrf-cloud/page/Devices/Properties/Types.html#mqtt-team-device) and for persistent MQTT sessions. The simulator also needs some extensive refactoring to simplify and clarify the code and operations.

Other improvements include:
* Local file storage of device credentials, whether generated locally or retrieved from the REST API
* Streamlined CLI and documentation
* Fixed https://github.com/nRFCloud/device-simulator-v2/issues/20

### CODE REVIEW

File: src/cli.ts [hunk 1]
```diff
@@ -1,164 +1,82 @@
...
+    .addOption(
+      new Option(
+        '-c, --certificate-type <certificateType>',
+        'Specifies the type of certificate you want created for your new device: self-signed certificate or one for Just-In-Time-Provisioning (JITP). The latter is discouraged, and is mainly for internal Nordic Semiconductor use.',
+      ).choices(['self-signed', 'JITP']).default('self-signed'),
     )
     .option(
-      '-s, --services <services>',
-      'Comma-delimited list of services to enable. Any of: [gps,gnss,acc,temp,device,rsrp,location,log,alert]',
+      '-p, --prevent-association <preventAssociation>',
```
Comment (sherretten) [inline src/cli.ts]: Should this just take a `-p` to be true? `-p true` feels wrong.
```suggestion
      '-p, --prevent-association',
```

**Review by sherretten — COMMENTED** [review]
I like a lot of these changes.

I really will miss being able to pass in a deviceId even if the certs haven't been created. Maybe if a user already generated device certs they could add them to the `/credentials` before running the simulator otherwise the simulator generates them for that specific deviceId?

File: src/cli.ts (hunk 1 above)
Comment (savvyintegrations) [reply src/cli.ts]: Good catch! Fixed.

**Comment by savvyintegrations** [comment]
>Maybe if a user already generated device certs they could add them to the /credentials before running the simulator

Yes, that's the idea. Allows total flexibility, as well as easier visibility about what devices you have the creds for.

**Comment by sherretten** [comment]
> Yes, that's the idea. Allows total flexibility, as well as easier visibility about what devices you have the creds for.

I more so meant, if they wanted to add the certs themselves then they could add them otherwise it will generate the certs for them. Does that make sense?

**Comment by savvyintegrations** [comment]
> I more so meant, if they wanted to add the certs themselves then they could add them otherwise it will generate the certs for them. Does that make sense?

Ah, I understand now. No problem: 7f538e7472e99c2625d9eb25ea65646c725053e2

**Review by sherretten — APPROVED** [review]

File: README.md [hunk 2]
```diff
@@ -4,282 +4,49 @@
...
-MESSAGE: [
-  ""
-]
-***************************************
+>[!NOTE]
+>Including `device` in the list will generate a LOT of device info messages which may overrun your Web browser. Best not to run it more than a few seconds with it, or you can leave out `device` and run it long-term.
 
-subscribed to "dev/<your_tenant_id>/<your_device_id>/jobs/rcv"
-```
+If you want to use different GPS data, replace the appropriate file in [./data/sensors](https://github.com/nRFCloud/device-simulator-v2/tree/saga/data/sensors) or change tne appropriate file path(s) in [cli.ts](src/cli.ts). (There is some additional GPS data in this repo for routes around Portland, Oregon, USA.)
```
Comment (lincolnthomas) [inline README.md]:
```suggestion
If you want to use different GPS data, replace the appropriate file in [./data/sensors](https://github.com/nRFCloud/device-simulator-v2/tree/saga/data/sensors) or change the appropriate file path(s) in [cli.ts](src/cli.ts). (There is some additional GPS data in this repo for routes around Portland, Oregon, USA.)
```

File: README.md [hunk 3]
```diff
@@ -4,282 +4,49 @@
...
-
-# compile
-yarn build
-
-# test
-node dist/cli.js <options>
+node dist/cli.js --help
 ```
-
-### Publishing
```
Comment (lincolnthomas) [inline README.md:102]: Don't we still need this section? Otherwise people who run it by `npx` won't see changes only committed to the repo. If we only want Nordicans to be able to publish, should we put this info in e.g. Confluence where outsiders can't see it?

File: README.md
Comment (lincolnthomas) [inline README.md:1]: Nice reduction and reorg here!

File: package.json
Comment (lincolnthomas) [inline package.json:1]: Nice upgrades of tools

File: src/app/services/Gnss.ts
Comment (lincolnthomas) [inline src/app/services/Gnss.ts:1]: So we never had message IDs this whole time?  Wow, good addition.

File: src/cli.ts [hunk 4]
```diff
@@ -1,164 +1,82 @@
...
-      'Specifies the shadow to use. For custom shadow, pass a JSON-encoded shadow object or relative path to json file. Otherwise, pass "mss" or "atv2" to automatically generate a conformal shadow',
-      handleAppType,
-    )
-    .option(
-      '-p, --job-execution-path <jobExecutionPath>',
-      'Specifies an unhappy job execution path for a fota update. View the "Use an unhappy path for FOTA execution" section of the README for more details.',
-      handleJobExecution,
-    )
+    .addOption(new Option(
+      '-a, --app-type <appType>',
```
Comment (lincolnthomas) [inline src/cli.ts:65]: The old `-t` option allowed for a user to pass a custom shadow, instead of simulating an `mss` or `atv2` shadow. So this PR removes that feature? Not sure if it was necessary anyway, it was a new feature recently. Users could create a simulated device and later change the shadow by other means.

File: src/index.ts [hunk 5]
```diff
@@ -1,333 +1,251 @@
...
+} from './sensors';
+
+export type DeviceType = 'Generic' | 'Team';
+export type CertificateType = 'Self-Signed' | 'JITP' | 'Non-JITP (AWS-Signed)';
+export interface DeviceCredentials {
+  caCert: string;
+  clientCert: string;
+  privateKey: string;
+}
+interface ConfigCommon {
```
Comment (lincolnthomas) [inline src/index.ts:32]: Good breakup of the 1 config into 3.

File: src/index.ts [hunk 6]
```diff
@@ -1,333 +1,251 @@
...
+  const stage = hostSplit.length === 3 ? 'prod' : hostSplit[1];
+  const teamData = await restApiClient.fetchTeamInfo();
+  const teamId = teamData.team.tenantId;
+  const teamName = teamData.team.name;
+  const mqttTopicPrefix = `${stage}/${teamId}`;
+  const mqttEndpoint = `mqtt${stage === 'prod' ? '' : `.${stage}`}.nrfcloud.com`;
+  let deviceId = simConfig.deviceId;
+  if (deviceId) {
+    simConfig.deviceCredentials = getLocallyStoredDeviceCredentials(deviceId, log);
+    if (!simConfig.deviceCredentials) {
```
Comment (lincolnthomas) [inline src/index.ts:78]: So if someone onboards, deletes, then re-onboards a device, will it use the old credentials? Even if they onboard it with a different tenant (API key)?

File: src/nrfDevice.ts [hunk 7]
```diff
@@ -136,31 +121,41 @@ export const nrfDevice = (
...
-    log.success('connected');
-    await notifyOfConnection('connect');
+    await handleConnect('connect');
   });
 
   client.on('message', (topic: string, payload: any) => {
     log.incoming(topic, payload || {});
     const p = payload ? JSON.parse(payload.toString()) : {};
+    if (topic.lastIndexOf('/c2d') > 0) {
+      topic = device.topics.c2d;
```
Comment (lincolnthomas) [inline src/nrfDevice.ts:131]: Why this? Seems to cut off any subtopics of `/c2d`

**Review by lincolnthomas — COMMENTED** [review]
Looks good except a few questions and nits. Lots of great refactoring making this easier to maintain & extend in the future. I can approve after your responses.

File: src/cli.ts (hunk 4 above)
Comment (savvyintegrations) [reply src/cli.ts:65]: Yeah, that was my thinking. Or they can just modify the code themselves.

File: src/nrfDevice.ts (hunk 7 above)
Comment (savvyintegrations) [reply src/nrfDevice.ts:131]: It's  b/c the subscription uses a wildcard, so the topic could end in anything, but the way listeners are registered requires a constant value like `c2d`. So I'm just ensuring that, regardless of the c2d topic the message is received on, it will evaluate to the key expected by the listener map.

File: src/index.ts (hunk 6 above)
Comment (savvyintegrations) [reply src/index.ts:78]: Onboards, deletes the device on nRF Cloud, then re-onboards? In that case, yes, it would work fine b/c all traces of the device were deleted. Or maybe I misunderstand your question?

File: README.md (hunk 3 above)
Comment (savvyintegrations) [reply README.md:102]: Yeah, I was wondering about this. I don't think we need it. No one outside of Nordic has ever contributed anyway.

Comment (savvyintegrations) [reply README.md:102]: Restored

**Review by lincolnthomas — APPROVED** [review]
Go for it!
